services: # Service MongoDB
    mongodb:
        image: mongo:8.0
        container_name: mongodb
        restart: always
        volumes:
            - mongodb_data:/data/db
        ports:
            - "27017:27017"
        networks:
            - app_network
        environment:
            - MONGO_INITDB_DATABASE=visioconf

    # Service Backend
    backend:
        build:
            context: ./BACKEND
            dockerfile: Dockerfile
        container_name: backend
        restart: always
        depends_on:
            - mongodb
        ports:
            - "3220:3220"
        networks:
            - app_network
        environment:
            - MONGO_URI=mongodb://mongodb:27017/visioconf
        env_file:
            - path: ./BACKEND/.env
              required: false
            - path: ./BACKEND/.env.dev
              required: false
            - path: ./BACKEND/.env.prod
              required: false
            - path: ./BACKEND/.env.local
              required: false
        
        volumes:
            - ./BACKEND:/app
            - /app/node_modules 

    # Service Frontend
    frontend:
        build:
            context: ./FRONTEND
            dockerfile: Dockerfile
        container_name: frontend
        restart: always
        depends_on:
            - backend
        ports:
            - "3000:3000"
        networks:
            - app_network
        env_file:
            - path: ./FRONTEND/.env
              required: false
            - path: ./FRONTEND/.env.dev
              required: false
            - path: ./FRONTEND/.env.prod
              required: false
            - path: ./FRONTEND/.env.local
              required: false
        
        volumes:
            - ./FRONTEND:/app
            - /app/node_modules

# Définition des volumes
volumes:
    mongodb_data:
        driver: local

# Définition des réseaux
networks:
    app_network:
        driver: bridge
